/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MinimalQuizPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  alignment: "center",
  blurBackground: true
};
var MinimalQuizPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MinimalQuizSettingTab(this.app, this));
    this.addRibbonIcon("checkbox-glyph", "Start quiz", () => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (activeView) {
        const editor = activeView.editor;
        this.startQuiz(editor);
      } else {
        new import_obsidian.Notice("No active markdown editor found.");
      }
    });
    this.addCommand({
      id: "show-questions-modal",
      name: "Start quiz on current file",
      editorCallback: (editor, view) => {
        this.startQuiz(editor);
      }
    });
  }
  startQuiz(editor) {
    var _a, _b;
    const content = editor.getValue();
    const qaMap = this.extractQuestionsAndAnswers(content);
    const entries = Array.from(qaMap.entries());
    if (entries.length > 0) {
      const filePath = (_b = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) != null ? _b : "unknown";
      new QuestionsModal(this.app, entries, this.settings, filePath).open();
    } else {
      new import_obsidian.Notice("No questions found.");
    }
  }
  extractQuestionsAndAnswers(content) {
    const qaMap = /* @__PURE__ */ new Map();
    const regex = /(.*\?)\n([\s\S]*?)(?=\n\n|$)/g;
    let match;
    while ((match = regex.exec(content)) !== null) {
      const question = match[1].trim();
      const answer = match[2].trim();
      if (question && answer) {
        qaMap.set(question, answer);
      }
    }
    return qaMap;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var QuestionsModal = class extends import_obsidian.Modal {
  constructor(app, questions, settings, sourcePath) {
    super(app);
    this.answerVisible = false;
    this.currentIndex = 0;
    this.entries = questions;
    this.settings = settings;
    this.component = new import_obsidian.Component();
    this.sourcePath = sourcePath;
  }
  onOpen() {
    const { modalEl } = this;
    const bgEl = modalEl.parentElement;
    if (bgEl && this.settings.blurBackground) {
      bgEl.classList.remove("quiz-no-blur");
      bgEl.classList.add("quiz-blur");
    } else if (bgEl) {
      bgEl.classList.remove("quiz-blur");
      bgEl.classList.add("quiz-no-blur");
    }
    this.scope.register([], "Enter", () => {
      this.toggleAnswer();
    });
    this.scope.register([], " ", () => {
      this.toggleAnswer();
    });
    this.render();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    if (this.currentIndex >= this.entries.length) {
      new import_obsidian.Notice("You finished the quiz - good job!");
      this.close();
      return;
    }
    const progressText = `${this.currentIndex + 1}/${this.entries.length}`;
    const progressEl = contentEl.createEl("div", {
      text: `Progress: ${progressText}`
    });
    progressEl.classList.add("quiz-progress");
    const [question, answer] = this.entries[this.currentIndex];
    const questionContainer = contentEl.createEl("div");
    this.renderQuestion(question, questionContainer);
    const answerContainer = contentEl.createEl("div");
    if (this.answerVisible) {
      this.renderAnswer(answer, answerContainer);
    }
    const isLastQuestion = this.currentIndex === this.entries.length - 1;
    const buttonText = this.answerVisible ? isLastQuestion ? "Finish quiz" : "Next question" : "Show answer";
    const button = contentEl.createEl("button", {
      text: buttonText
    });
    button.classList.add("quiz-button");
    button.addEventListener("click", () => this.toggleAnswer());
    contentEl.classList.remove("quiz-align-left", "quiz-align-center");
    contentEl.classList.add(
      this.settings.alignment === "center" ? "quiz-align-center" : "quiz-align-left"
    );
  }
  renderQuestion(question, questionContainer) {
    this.component.load();
    import_obsidian.MarkdownRenderer.render(this.app, question, questionContainer, this.sourcePath, this.component);
  }
  renderAnswer(answer, answerContainer) {
    this.component.load();
    import_obsidian.MarkdownRenderer.render(this.app, answer, answerContainer, this.sourcePath, this.component);
  }
  toggleAnswer() {
    if (this.answerVisible) {
      this.currentIndex++;
      this.answerVisible = false;
    } else {
      this.answerVisible = true;
    }
    this.render();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.component.unload();
  }
};
var MinimalQuizSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Modal alignment").setDesc("Choose the alignment of the modal content.").addDropdown(
      (dropdown) => dropdown.addOption("left", "Left").addOption("center", "Center").setValue(this.plugin.settings.alignment).onChange(async (value) => {
        this.plugin.settings.alignment = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Blur background").setDesc("Enable or disable background blur when the modal is open.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.blurBackground).onChange(async (value) => {
        this.plugin.settings.blurBackground = value;
        await this.plugin.saveSettings();
      })
    );
  }
};


/* nosourcemap */